name: flutter_sixvalley_ecommerce
description: A new Flutter setup application for starting a project.

publish_to: "none"

version: 1.0.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  provider: ^6.0.3
  connectivity: ^3.0.3
  dio: ^5.0.1
  http: ^0.13.1
  freezed: ^2.0.3+1
  line_icons:
  flutter_staggered_grid_view: ^0.4.1
  water_drop_nav_bar:
  shared_preferences: ^2.0.5
  fancy_bottom_navigation: ^0.3.3
  carousel_slider: ^4.0.0-nullsafety.0
  shimmer: ^2.0.0-nullsafety.0
  url_launcher: ^6.0.2
  image_picker: ^0.8.4+8
  webview_flutter: ^3.0.0
  flutter_html: ^3.0.0-alpha.3
  share: ^2.0.1
  photo_view: ^0.14.0
  package_info: ^2.0.0
  firebase_core: ^2.7.0
  firebase_messaging: ^14.2.5
  flutter_local_notifications: ^13.0.0
  path_provider: ^2.0.1
  google_sign_in: ^6.0.2
  flutter_facebook_auth: ^5.0.8
  flutter_svg: ^1.0.3
  phone_number: ^1.0.0
  country_code_picker: ^2.0.2
  pin_code_fields: ^7.0.0
  google_maps_flutter: ^2.0.3
  flutter_google_places: ^0.3.0
  geocoding: ^2.0.0
  geolocator: ^9.0.2
  flutter_typeahead: ^4.0.0
  marquee: ^2.2.1
  flutter_rating_bar: ^4.0.0
  flutter_widget_from_html: ^0.9.1
  flutter_widget_from_html_core: ^0.9.1
  flutter_html_table: ^3.0.0-alpha.3
  fluttertoast: ^8.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/language/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/ubuntu/Ubuntu-Regular.ttf
          weight: 400
        - asset: assets/fonts/ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/ubuntu/Ubuntu-Bold.ttf
          weight: 600
